### ISSUE TITLE
reverted PR

### ISSUE THREAD

**Issue by idrp** [qbcore-framework/qb-hotdogjob#26]
![image](https://user-images.githubusercontent.com/88186466/150710119-4806315f-b7ab-4426-9938-8719cb31a574.png)

the PR I put in removed this error, and allowed the Hotdog Job rep to work, what am I missing as it was reverted and I now get the error again.

Regards ZenKat

**Comment by Demo4889** [comment]
@idrp After looking into the reverted PR, I am seeing the 2 lines that were changed being

line removed    `local MyRep = PlayerData.metadata["hotdog"]`
line added    `local MyRep = PlayerData.metadata["jobrep"]["hotdog"]`

when you check the database for player metadata, the job rep is within the jobrep table in the metadata. the reversion added the ["jobrep"] back in so it doesn't cause any issues getting the job rep for that player.

**Comment by BerkieBb** [comment]
You don't need to look in the database to see that, qb-core/server/player.lua already tells you where everything is located
