### ISSUE TITLE
No blip, needs adding to city hall

### ISSUE THREAD

**Issue by Andyauk** [qbcore-framework/qb-hotdogjob#32]
I guess this was intended to be added into city hall. as you cant get this job, without doing setjob, or adding into city hall.

**Comment by RailedFromBehind** [comment]
isnt the job public? i swear u can just walk up to the thingy and start, like its not actually a 'job' or am i just talking shite?

**Comment by Andyauk** [comment]
> isnt the job public? i swear u can just walk up to the thingy and start, like its not actually a 'job' or am i just talking shite?

Your right, it's how it always ways, but the update it had, locked it behind getting it from city hall, but it wasn't added to city hall.

**Comment by Andyauk** [comment]
I ended up putting, this into server main of city hall. Line9.
`    ["hotdog"] = "Hot Dog",`

As this code is now locked behind 
`if PlayerData.job.name == 'hotdog' then`

**Comment by tom-osborne** [comment]
Completed in https://github.com/qbcore-framework/qb-hotdogjob/pull/36 and https://github.com/qbcore-framework/qb-cityhall/pull/73
