### ISSUE TITLE
Missing job markers

### ISSUE THREAD

**Issue by CottonMouthMax** [qbcore-framework/qb-hotdogjob#34]
I have the file in my qb folder and im at the location that is marked in the config. but i don't see a marker or anything to start the job. Am i missing something?

**Comment by Andyauk** [comment]
> I have the file in my qb folder and im at the location that is marked in the config. but i don't see a marker or anything to start the job. Am i missing something?

If you look in my post in issues, below yours you will see it needs to be added into city hall.

**Comment by tom-osborne** [comment]
Completed in https://github.com/qbcore-framework/qb-cityhall/pull/73 and https://github.com/qbcore-framework/qb-hotdogjob/pull/36
