### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GoPuma21** [qbcore-framework/qb-hotdogjob#41]
**Describe the bug**
Character get's stuck in the air after selling hotdogs to NPC's

**Expected behavior**
I should be able to move my cart after selling to NPC but instead of that my character gets stuck in the air

**Screenshots**
https://medal.tv/games/gta-v/clips/v2Baie778A3gr/d1337y7KsO1W?invite=cr-MSxENVAsMjY3MTQxMDcs

**Questions (please complete the following information):**
 - When you last updated: 02/08/2022
 - Are you using custom resource? which ones? qb-target edited is the only thing could make some issue with this script but I tried the script on fresh server with updated scripts, original target and the same thing is happening. 
 - Have you renamed `qb-` to something custom? no

**Additional context**
Tried a lot of ways to fix it but im lost

**Comment by GoPuma21** [comment]
Seems like I did not have target enabled on server config. the hotdog job did not with target and that was the issue. 
Tested by me and tomorrow gonna close the thread if works with 10 people working over.

**Comment by tom-osborne** [comment]
I was able to replicate this on an older version, but cannot replicate it with the latest version with either target enabled or disabled.

**Comment by GoPuma21** [comment]
Issue got fix by enabling target from config server. Somehow non-target version of Hotdog did not work for me.
