### ISSUE TITLE
[BUG] Not being able to grab cart

### ISSUE THREAD

**Issue by Sqrl34** [qbcore-framework/qb-hotdogjob#52]
**Describe the bug**
On fresh install, I am not able to grab the hotdog cart but am able to cook hotdogs

**To Reproduce**
1. Go to H blip and go on duty
2. go to the cart
3. Try and grab the stall but says that there is no vehicle near by

**Expected behavior**
I expected to be able to pick up the cart and move about the city selling hotdogs

**Screenshots**
Going on duty and trying to move the cart
https://gyazo.com/cb5138ad2982684ae44352455b1aa8ef

**Comment by singh-manavv** [comment]
Unable to reproduce the issue , make sure you have the latest version of the script and other core scripts.

**Comment by S33G** [comment]
@Sqrl34 Did updating fix the issue you were facing?

**Comment by GodyFromDiscord** [comment]
Cannot reproduce at all
