### ISSUE TITLE
[BUG] Missing properCollision Detection of the hotdog stall

### ISSUE THREAD

**Issue by antpngl92** [qbcore-framework/qb-hotdogjob#55]
**Describe the bug**
There seems to be missing proper collision detection on the stall. The stall gets weird when bumping into NPCs while runnig.  

**To Reproduce**
1. Go to Hotdog job
2. Start your shift
3. Grab a stall
4. Run against NPCs
5. See error

**Expected behavior**
Proper collision

**Video**
https://www.youtube.com/watch?v=OicEtpkSlXc

**Comment by GodyFromDiscord** [comment]
Thanks for the issue, however when trying to add collision to the object when it is attached, it gives the player a strange collision where when running into cars and whatnot the cars are flipped, street objects like bins and lamposts are knocked down as well, plus the hotdog stand returns to its normal state after 150MS anyway if knocked, so this will be closed
